### ISSUE TITLE
Definir ranqueamentos que serão suportados

### ISSUE THREAD

**Issue by luishgh** [pds2/20231-team-1#2]
Definir quais serão os ranqueamentos que serão suportados. O **TF-IDF** e o **BM25** seriam o mínimo, mas talvez convenha adicionar suporte a algum outro também.

**Comment by souza-marcos** [comment]
Nas minhas buscas, ocorreu com certa frequência **LSI** (Latent Semantic Indexing). Porém me pareceu que é mais complexo do que se espera para este projeto, então não sei se é viável adicioná-lo também.

**Comment by luishgh** [comment]
Dei uma lida no artigo e acho que é viável adicionar o LSA/LSI. No caso ele seria uma alternativa ao Modelo de Espaço Vetorial. Podemos ter uma classe base para os modelos de comparação, que é herdada pela classe do Modelo Vetorial e pela classe do LSA/LSI, e outra classe base para os modelos de ponderação, que é herdada pela classe do TF-IDF e pela do BM25. Por fim, instâncias dessas duas classes agiriam em conjunto para fornecer um ranqueamento.

**Comment by souza-marcos** [comment]
Fica decidido então que vamos utilizar:

-  TF-IDF e BM25 como modelos de ponderamento, e
-  LSA/LSI e Espaço vetorial simples como  modelos de ranqueamento.
